### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Artem13327** [Sweeistaken/Dice-App#1]
Someone filed a request to add an app to F-Droid https://gitlab.com/fdroid/rfp/-/issues/2472 but the app doesn't have a license, please fix it

**Comment by Sweeistaken** [comment]
Hi.
Sorry for the inconvenience, i do not add licenses to my software yet.

**Comment by Sweeistaken** [comment]
@Artem13327 Hi, I filed that request, and I have updated the issue with the new license I added to my repo.
